version: "3.3"
services:
        nginx:
                build: ./requirements/nginx
                image: inception_nginx
                networks :
                  - inception_network
                ports:
                  - "443:443"
                restart: always
        php:
                build: ./requirements/wordpress
                image: inception_php
                networks :
                  - inception_network
                restart: always


volumes:
        wp-data:
                driver: local
                driver_opts:
                        type: none
                        device: 

networks:
        inception_network:
                 driver: bridge
        
