version: "3.3"
services:
        nginx:
                depends_on:
                        - php
                build: ./requirements/nginx
                image: inception_nginx
                networks :
                  - inception_network
                ports:
                  - "443:443"
                restart: always
                volumes:
                  - wp-data:/var/www/html

        php:
                build: ./requirements/wordpress
                image: inception_php
                networks :
                  - inception_network
                restart: always
                volumes:
                  - wp-data:/var/www/html


volumes:
        wp-data:
                driver: local
                driver_opts:
                        type: none
                        device: /home/ericard/data/wp-data
                        o: bind 

networks:
        inception_network:
                 driver: bridge
        
