version: "3.3"
services:
        nginx:
                depends_on:
                  - php
                build: ./requirements/nginx
                image: inception_nginx
                networks :
                  - inception_network
                ports:
                  - "443:443"
                restart: always
                volumes:
                  - wp-data:/var/www/html

        php:
                depends_on:
                  - mariadb
                build: ./requirements/wordpress
                image: inception_php
                env_file:
                  - .env
                networks :
                  - inception_network
                restart: always
                volumes:
                  - wp-data:/var/www/html
        
        mariadb:
                build: ./requirements/mariadb
                image: inception_mariadb
                env_file:
                  - .env
                networks :
                  - inception_network
                restart: always
                volumes:
                  - db:/var/lib/mysql


volumes:
        wp-data:
                driver: local
                driver_opts:
                        type: none
                        device: /home/ericard/data/wp-data
                        o: bind 

        db:
                driver: local
                driver_opts:
                        type: none;
                        device: /home/ericard/data/db
                        o: bind

networks:
        inception_network:
                 driver: bridge
