version: "3.3"
services:
        nginx:
                build: ./requirements/nginx
                image: inception_nginx
                networks :
                  - inception_network
                ports:
                  - "443:443"
                restart: always
        php:
                build: ./requirements/wordpress
                image: inception_php
                networks :
                  - inception_network
                restart: always

networks:
        inception_network:
                 driver: bridge
        
